### ISSUE TITLE
Pressing `Enter` on line with `--` or `**` unintentionally deletes  the text.

### ISSUE THREAD

**Issue by catnose99** [steelydylan/react-split-mde#14]
![](https://user-images.githubusercontent.com/6715229/117817628-bcfbd980-b2a2-11eb-96fe-6f7f7d3c21c2.gif)

ref: https://github.com/zenn-dev/zenn-community/issues/297

**Comment by steelydylan** [comment]
@catnose99 おおそんなバグが。今日明日くらいでなおしとくわ

**Comment by catnose99** [comment]
いきなりコミットしてしまった
https://github.com/steelydylan/react-split-mde/commit/f6e06e11a184abb3c7e450150a2363c0e2c1a5d5

**Comment by steelydylan** [comment]
@catnose99 masterからhotfix/0.3.4っていう名前でブランチを作ってもらってpackage.jsonを0.3.4にしてPRしてmasterにマージされると、新しいバージョンがリリースされるはず！
